# 0. Introduction

In [6]:
import numpy as np
from matersdk.io.pwmat.output.movement import Movement
from matersdk.data.deepmd.data_system import DeepmdDataSystem

# 1. Demo 1: 根据 Movement 文件，生成 550 个Image文件夹。文件夹内存储一些重要信息

In [2]:
movement = Movement(movement_path="/data/home/liuhanyu/hyliu/code/mlff/test/demo2/PWdata/data1/MOVEMENT")
dp_data_system = DeepmdDataSystem.from_trajectory(trajectory_object=movement)
dir_path = "/data/home/liuhanyu/hyliu/code/test"

### Step 1.
print()
print("Step 1. ")
dp_data_system.save(dir_path=dir_path)


### Step 2.
print()
print("Step 2. The atomic number in system:", end='\t')
print(dp_data_system.atomic_numbers_lst)


### Step 3.
print()
print("Step 3. The number of atoms in system:", end='\t')
print(dp_data_system.num_atoms)


Step 1. 

Step 2. The atomic number in system:	[3, 14]

Step 3. The number of atoms in system:	72


## 1.1. 查看 `DeepmdDataSystem.save()` 的保存结果

In [5]:
import os 

os.listdir(dir_path)    # 查看所有 Image 的文件夹
os.listdir( os.path.join(dir_path, "102"))  # 查看 Image 102 的文件夹

['atomic_force.npy',
 'atomic_number.npy',
 'nbrs_distances.npy',
 'energy.npy',
 'box.npy',
 'virial.npy',
 'atom.config',
 'coord.npy',
 'nbrs_coords.npy',
 'nbrs_atomic_numbers.npy',
 'atomic_energy.npy']

In [9]:
# 1. 
print("1. The box of Image 102:")
print(np.load(os.path.join(dir_path, "102", 'box.npy')))

1. The box of Image 102:
[[3.00000e+00 1.78000e-04 6.66514e-01]
 [3.00000e+00 2.49909e-01 1.66180e-01]
 [3.00000e+00 4.99893e-01 6.65612e-01]]


In [11]:
# 2. 
#   第一项：总能
#   第二项：动能
#   第三项：势能
print("2. The energy of Image 102:")
print(np.load(os.path.join(dir_path, "102", 'energy.npy')))

1. The energy of Image 102:
[-11869.05537    -11885.89496        16.83959066]


In [14]:
# 3. 
#   一维：各个原子
#   二维：分别对应x, y, z坐标
print("3. The coordinates of atoms in Image 102:")
print(np.load(os.path.join(dir_path, "102", 'coord.npy')))

1. The coordinates of atoms in Image 102:
[[1.3089764  0.05369358 0.20819837]
 [3.57450993 0.17866366 0.45670475]
 [2.77780461 0.05168675 0.53607602]
 [2.07841537 0.17772441 0.13135333]
 [2.16400852 0.19614065 0.39539191]
 [4.39308493 0.32000716 0.64513427]
 [3.68526745 0.19467581 0.73667174]
 [2.94041958 0.32090743 0.31838545]
 [3.60631233 0.27084664 0.38753764]
 [2.84252547 0.14688972 0.46927211]
 [5.16883738 0.27425776 0.73133598]
 [1.41674427 0.14940675 0.14497417]
 [0.63849991 0.10489061 0.14052017]
 [2.84716564 0.22759479 0.38474616]
 [2.13483953 0.10201263 0.47340096]
 [4.31621825 0.22514759 0.71342091]
 [4.08274125 0.17881957 0.90275609]
 [3.27463674 0.29987155 0.48062039]
 [5.58439944 0.42938452 0.74035802]
 [4.80443825 0.30357626 0.81750989]
 [7.91926263 0.57256623 1.25959605]
 [4.21095211 0.44731813 0.6835939 ]
 [6.40635931 0.57239484 0.92431067]
 [5.6782487  0.44664622 1.0088405 ]
 [2.6816674  0.27553243 0.50729332]
 [4.87564501 0.39351998 0.75295049]
 [4.1147202  0.2684054

In [18]:
# 4. 
print("4. The virial tensor of Image 102:")
print(np.load(os.path.join(dir_path, "102", 'virial.npy')))

1. The virial tensor of Image 102:
[[-0.8118    -0.0473205  3.86676  ]
 [-0.0466689 14.9038     4.38904  ]
 [ 3.86699    4.38978   11.6277   ]]


In [20]:
# 5. 
#   Note: 按照原子序数从小到大排列
print("5. The atomic_number in Image 102:")
print(np.load(os.path.join(dir_path, "102", 'atomic_number.npy')))

1. The atomic_number in Image 102:
[ 3 14]


In [22]:
# 6. atomic_force.npy
#   第一维：各个原子
#   第二维：原子在x, y, z方向上的受力
print("6. The atomic force of atoms in Image 102:")
print(np.load(os.path.join(dir_path, "102", 'atomic_force.npy')))

6. The atomic force of atoms in Image 102:
[[-0.06586582 -0.04867223 -0.0109084 ]
 [-0.06470087  0.19711851 -0.03448263]
 [-0.28057063 -0.2339251  -0.01771066]
 [ 0.20091121 -0.16499159  0.10400352]
 [-0.28312376  0.18280265 -0.11210828]
 [-0.10079384 -0.10909601 -0.01758642]
 [ 0.30956644 -0.06286156 -0.02622806]
 [ 0.1580531  -0.00770516 -0.1333077 ]
 [-0.03312929 -0.02352935  0.03252365]
 [-0.03083894 -0.06967411  0.18703552]
 [ 0.04818054  0.08296857  0.19741526]
 [ 0.09389846  0.10021862  0.00377701]
 [-0.00591945 -0.03524654  0.23434704]
 [-0.08899155 -0.13529594  0.12920001]
 [ 0.0907831   0.03114225 -0.12713077]
 [-0.05490218 -0.11457357 -0.00518913]
 [-0.0790145   0.27388407 -0.17701832]
 [-0.18080381 -0.13633886 -0.10702038]
 [ 0.15971493 -0.08030691  0.17793019]
 [-0.16294446 -0.06222301  0.16589154]
 [-0.14092638 -0.07390265 -0.01741148]
 [ 0.27244547  0.04349031 -0.06714979]
 [-0.16530383 -0.0321763   0.06744691]
 [-0.09150793  0.08818434 -0.14858177]
 [ 0.04392977  0.1220

In [24]:
# 7. atomic_energy.npy
print("7. The atomic energy of atoms in Image 102:")
print(np.load(os.path.join(dir_path, "102", 'atomic_energy.npy')))

7. The atomic energy of atoms in Image 102:
[-190.94682214 -190.95479726 -190.93950339 -190.96443162 -190.95974719
 -190.93836063 -190.99728147 -190.95179131 -191.07767964 -191.061279
 -191.05533569 -191.08381639 -191.12455006 -191.07554098 -191.074678
 -191.06807252 -191.03973056 -190.96084509 -190.93630381 -190.91884649
 -190.96476432 -190.96788836 -190.98343883 -190.94639359 -191.07679212
 -191.04596868 -191.08195501 -191.03362294 -191.04225738 -191.05459775
 -191.05879505 -191.0475977  -190.96423224 -190.93699595 -190.96121932
 -190.9738209  -190.94379448 -190.93150604 -190.94270358 -190.97637474
 -191.0575086  -191.06549771 -191.07876824 -191.03289709 -191.0797894
 -191.06458788 -191.07581396 -191.0662353  -113.2027685  -113.4039092
 -113.2516814  -112.9050468  -113.2795952  -113.4123896  -113.2107131
 -113.4860111  -112.9327323  -113.2740204  -113.3431241  -113.1086516
 -113.0186464  -113.3092843  -113.0899562  -113.3295582  -113.1763475
 -113.2279722  -113.0332642  -113.2936491 

In [28]:
# 8. 
#   第一维：对应体系内的所有原子
#   第二维：原子的近邻原子的原子序数（按照距离，从小到大排列）
print("8. The nbrs_atomic_number in Image 102:")
print(np.load(os.path.join(dir_path, "102", 'nbrs_atomic_numbers.npy')))

8. The nbrs_atomic_number in Image 102:
[[ 3. 14.  3. ... 14.  3.  3.]
 [ 3.  3. 14. ... 14.  3.  3.]
 [ 3. 14.  3. ... 14.  3.  3.]
 ...
 [14.  3.  3. ...  3.  3.  3.]
 [14.  3.  3. ...  3.  3.  3.]
 [14.  3.  3. ...  3.  3.  3.]]


In [29]:
# 9. 
#   第一维：对应体系内的所有原子
#   第二维：原子的近邻原子距中心原子的距离（按照距离，从小到大排列）
print("9. The nbrs_atomic_distances in Image 102:")
print(np.load(os.path.join(dir_path, "102", 'nbrs_distances.npy')))

9. The nbrs_atomic_distances in Image 102:
[[ 0.          0.11866519  0.15739195 ... 15.14916484 15.68953876
  15.86795551]
 [ 0.          0.1195541   0.12115569 ... 12.87245706 13.41285476
  13.58993749]
 [ 0.          0.12907849  0.1330983  ... 13.65193833 14.19372351
  14.37123619]
 ...
 [ 0.          0.1176223   0.23800051 ... 12.89053141 12.99467505
  13.65920635]
 [ 0.          0.11866519  0.22471751 ... 12.57594366 12.75733605
  12.93771368]
 [ 0.          0.12115569  0.23584772 ... 14.44898669 14.55186854
  15.21724924]]


In [32]:
# 10. 
#   第一维：对应体系内的所有原子
#   第二维：原子的近邻原子的笛卡尔坐标（按照距离，从小到大排列）
#   第三维：分别对应 x, y, z 坐标
print("10. The nbrs_atomic_coords in Image 102:")
print(np.load(os.path.join(dir_path, "102", 'nbrs_coords.npy')))

10. The nbrs_atomic_coords in Image 102:
[[[ 1.3089764   0.05369358  0.20819837]
  [ 1.31838874 -0.02977298  0.29202061]
  [ 1.41674427  0.14940675  0.14497417]
  ...
  [16.1910719   1.28253728  2.75974141]
  [16.72121585  1.44901131  2.79230167]
  [16.91926263  1.32254623  2.75790205]]

 [[ 3.57450993  0.17866366  0.45670475]
  [ 3.60631233  0.27084664  0.38753764]
  [ 3.58609512  0.09597838  0.54449785]
  ...
  [16.1910719   1.28253728  2.75974141]
  [16.72121585  1.44901131  2.79230167]
  [16.91926263  1.32254623  2.75790205]]

 [[ 2.77780461  0.05168675  0.53607602]
  [ 2.81478221 -0.03184006  0.62727463]
  [ 2.84252547  0.14688972  0.46927211]
  ...
  [16.1910719   1.28253728  2.75974141]
  [16.72121585  1.44901131  2.79230167]
  [16.91926263  1.32254623  2.75790205]]

 ...

 [[ 5.05697251  0.59255251  0.87531818]
  [ 5.07841537  0.67761741  0.79696533]
  [ 5.16400852  0.69603365  1.06100391]
  ...
  [-7.58325573 -0.60057325 -1.35333183]
  [-7.6910236  -0.69628642 -1.29010763]
  [