# 0. Introduction
1. We write `DeepmdSeTildeR` to construct the $\widetilde{R}$ in `DeepPot-SE`

In [1]:
from timeit import default_timer as timer
from matersdk.io.publicLayer.structure import DStructure
from matersdk.io.publicLayer.neigh import StructureNeighborsDescriptor
from matersdk.feature.deepmd.se import DeepmdSeTildeR

# 1. Demo for `DeepmdSeTildeR`
1. Running time (550, 1 core, 1  process)      =  85.41465628892183   s
2. Running time (550, 1 core, 4  processes)    =  24.182958006858826  s
3. Running time (550, 1 core, 20 processes)    =   5.985623575747013  s
4. Running time (550, 1 core, 26 processes)    =   5.2559670731425285 s  (0.01s per structure)

In [2]:
atom_config_path = "/data/home/liuhanyu/hyliu/code/matersdk/demo/feature/movement/LiSi.config"
scaling_matrix = [3, 3, 3]
reformat_mark = True
n_neighbors = 200
coords_are_cartesian = True

center_atomic_number = 3    # Li
nbr_atomic_number = 14      # Si
rcut = 10
rcut_smooth = 9.5
max_num_nbrs = 100

_start = timer()
structure = DStructure.from_file(
                file_format="pwmat",
                file_path=atom_config_path)
struct_nbr = StructureNeighborsDescriptor.create(
                'v2',
                structure=structure,
                scaling_matrix=scaling_matrix,
                reformat_mark=reformat_mark,
                n_neighbors=n_neighbors,
                #algorithm=algorithm,
                coords_are_cartesian=coords_are_cartesian)
deepmd_se_r = DeepmdSeTildeR(
                structure_neighbors=struct_nbr,
                center_atomic_number=center_atomic_number,
                nbr_atomic_number=nbr_atomic_number,
                rcut=rcut,
                rcut_smooth=rcut_smooth,
                max_num_nbrs=max_num_nbrs)

_end = timer()
#print(deepmd_se_r.dp_feature_pair_an)
#print(deepmd_se_r.dp_feature_pair_d)
#print(deepmd_se_r.dp_feature_pair_rc)
print("1.1. R in DeepPot-SE")
print(deepmd_se_r.dp_feature_pair_tildeR)
print("\n\n")
print("Running time = {0} s".format(_end - _start))

1.1. R in DeepPot-SE
[[[ 0.38989146  0.32687363 -0.18861164  0.09795218]
  [ 0.3876594  -0.3245613  -0.18864416  0.09671171]
  [ 0.37817839  0.01436821  0.36341413  0.1036466 ]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.38845326  0.01132949  0.37101977  0.11450724]
  [ 0.37867847  0.30257434 -0.19743547  0.11342568]
  [ 0.37223559 -0.29759346 -0.19098885  0.11627866]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.39670084 -0.33035184 -0.19113575  0.10819586]
  [ 0.38484031  0.32345499 -0.18203168  0.10170251]
  [ 0.37454811  0.01526631  0.36036188  0.10095814]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 ...

 [[ 0.3817733

/data/home/liuhanyu/anaconda3/envs/mlff/lib/python3.8/site-packages/matersdk/feature/deepmd/se.py:122: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(self.dp_feature_pair_d)
/data/home/liuhanyu/anaconda3/envs/mlff/lib/python3.8/site-packages/matersdk/feature/deepmd/se.py:176: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(self.dp_feature_pair_d)


# 2. Multiprocesses

In [4]:
from multiprocessing import Pool

In [6]:
def calculate_deepmd_se_r(
                file_format:str,
                file_path:str,
                scaling_matrix,
                reformat_mark:bool,
                n_neighbors:int,
                coords_are_cartesian:bool,
                center_atomic_number:int,
                nbr_atomic_number:int,
                rcut:float,
                rcut_smooth:float,
                max_num_nbrs:int):
    structure = DStructure.from_file(
                    file_format=file_format,
                    file_path=file_path)
    struct_nbr = StructureNeighborsDescriptor.create(
                    'v2',
                    structure=structure,
                    scaling_matrix=scaling_matrix,
                    reformat_mark=reformat_mark,
                    n_neighbors=n_neighbors,
                    #algorithm=algorithm,
                    coords_are_cartesian=coords_are_cartesian)
    deepmd_se_r = DeepmdSeTildeR(
                    structure_neighbors=struct_nbr,
                    center_atomic_number=center_atomic_number,
                    nbr_atomic_number=nbr_atomic_number,
                    rcut=rcut,
                    rcut_smooth=rcut_smooth,
                    max_num_nbrs=max_num_nbrs)



if __name__ == "__main__":
    atom_config_path = "/data/home/liuhanyu/hyliu/code/matersdk/demo/feature/movement/LiSi.config"
    scaling_matrix = [3, 3, 3]
    reformat_mark = True
    n_neighbors = 200
    coords_are_cartesian = True

    center_atomic_number = 3    # Li
    nbr_atomic_number = 14      # Si
    rcut = 10
    rcut_smooth = 9.5
    max_num_nbrs = 100

    _start = timer()
    parameters_lst = [("pwmat", atom_config_path, scaling_matrix, reformat_mark, n_neighbors, coords_are_cartesian, center_atomic_number,
                    nbr_atomic_number, rcut, rcut_smooth, max_num_nbrs) for _ in range(550)]
    with Pool(processes=26) as pool:
        pool.starmap(calculate_deepmd_se_r, parameters_lst)

    _end = timer()
    #print(deepmd_se_r.dp_feature_pair_an)
    #print(deepmd_se_r.dp_feature_pair_d)
    #print(deepmd_se_r.dp_feature_pair_rc)
    print("1.1. R in DeepPot-SE")
    print(deepmd_se_r.dp_feature_pair_tildeR)
    print("\n\n")
    print("Running time = {0} s".format(_end - _start))

/data/home/liuhanyu/anaconda3/envs/mlff/lib/python3.8/site-packages/matersdk/feature/deepmd/se.py:122: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(self.dp_feature_pair_d)
/data/home/liuhanyu/anaconda3/envs/mlff/lib/python3.8/site-packages/matersdk/feature/deepmd/se.py:122: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(self.dp_feature_pair_d)
/data/home/liuhanyu/anaconda3/envs/mlff/lib/python3.8/site-packages/matersdk/feature/deepmd/se.py:122: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(self.dp_feature_pair_d)
/data/home/liuhanyu/anaconda3/envs/mlff/lib/python3.8/site-packages/matersdk/feature/deepmd/se.py:176: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(self.dp_feature_pair_d)
/data/home/liuhanyu/anaconda3/envs/mlff/lib/python3.8/site-packages/matersdk/feature/deepmd/se.py:122: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(self.dp_feature_pair_d)


1.1. R in DeepPot-SE
[[[ 0.38989146  0.32687363 -0.18861164  0.09795218]
  [ 0.3876594  -0.3245613  -0.18864416  0.09671171]
  [ 0.37817839  0.01436821  0.36341413  0.1036466 ]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.38845326  0.01132949  0.37101977  0.11450724]
  [ 0.37867847  0.30257434 -0.19743547  0.11342568]
  [ 0.37223559 -0.29759346 -0.19098885  0.11627866]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.39670084 -0.33035184 -0.19113575  0.10819586]
  [ 0.38484031  0.32345499 -0.18203168  0.10170251]
  [ 0.37454811  0.01526631  0.36036188  0.10095814]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 ...

 [[ 0.3817733